name: Change Project Name
# env:
#   PROJECT_NAME: Monday

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      appName:
        description: 'New app name that you want to change'
        required: true
        default: 'testingAppName'

      branchName:
        description: 'Github branch name'
        required: true
        default: 'branchName'
jobs:
  rename-roject-name:
    name: Project Rename
    runs-on: macOS-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v2

      - name: Set up our JDK environment # setup JDK environment: mandatory as we need to build  android project
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Change App name
        run: sh ./.github/scripts/rename-app-name.sh ${{ github.event.inputs.appName }}

      - name: Clean Project
        run: sh ./.github/scripts/clean.sh

      - name: Install npm dependencies
        run: npm install --legacy-peer-deps

      - name: Change Splash Screen
        run: sh ./.github/scripts/change-splash-screen.sh

      - name: Change App Icon
        run: sh ./.github/scripts/set-app-icon.sh

      - name: Generate signed APK
        run: cd android && ./gradlew app:assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
          name: Generated Apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b action
          git commit -m "Add changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
