name: Change Project Name
# env:
#   PROJECT_NAME: Monday

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  rename-roject-name:
    name: Project Rename
    runs-on: macOS-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v2

      - name: Set up our JDK environment # setup JDK environment: mandatory as we need to build  android project
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Change App name
        run: sh ./.github/scripts/rename-app-name.sh testApplication

      - name: Clean Project
        run: sh ./.github/scripts/clean.sh

      - name: Install npm dependencies
        run: npm install --legacy-peer-deps

      - name: Generate signed APK
        run: cd android && ./gradlew app:assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
          name: testApplication-app.apk
          path: android/app/build/outputs/apk/release/app-release.apk
      # - name: Change Splash Screen
      #   run: sh ./.github/scripts/change-splash-screen.sh
