name: Push To Github
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout Current Repository
        uses: checkout/checkout@v2
        with:
         path: ./source-repo/
        
      - name: Commit files
        run: |
          git config --local user.email "abdulrauf_vhora@codenticsoftware.com"
          git config --local user.name "abdul"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: Abdulrauf-vhora/demo-APP@main
        with:
          branch: main
          github_token: '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'
