name: Push To Github
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: chekout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Create local changes
        run: |
          ... 
      - name: Commit files
        run: |
          git config --local user.email "abdulrauf_vhora@codenticsoftware.com"
          git config --local user.name "Abdulrauf-vhora"
          git commit -m "Add changes"
      - name: Push changes
        uses: Abdulrauf-vhora/demo-APP@main
        with:
          github_token: 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
          branch: main
