name: Push To Github
on:
  push:
    branches:
      - main
jobs:
  release:
    name: publish
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
 
      - name: Commit files
        run: |
          git config --local user.email "abdulrauf_vhora@codenticsoftware.com"
          git config --local user.name "Abdulrauf-vhora"
          git commit -m "Add changes"
      - name: Push changes
        uses: Abdulrauf-vhora/demo-APP@main
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
